version: "3.9"
services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamerag
    ports:
      - "5433:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
volumes:
  pgvector-data:
