version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:latest
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage
volumes:
  qdrant-storage:
