// Auto-generated by scripts/generate-metropolis-npcs.js -- do not edit by hand.
// The bounded set of real, backend NpcAgent archetypes that the ambient instanced crowd
// in metropolis.html shares. Each of the hundreds of visible crowd figures is tagged with
// one of these archetype ids at spawn (see game-engine.js addCrowd); clicking/talking to
// any figure calls /ask against its archetype's single shared NpcAgent, so the number of
// real backend agents stays fixed at roster.length regardless of how large the crowd is.
window.GAMERAG_METROPOLIS_ROSTER = [
  {
    "id": "street-food-vendor",
    "role": "street food vendor"
  },
  {
    "id": "taxi-dispatcher",
    "role": "taxi dispatcher"
  },
  {
    "id": "newsstand-owner",
    "role": "newsstand owner"
  },
  {
    "id": "office-worker-on-a-lunch-break",
    "role": "office worker on a lunch break"
  },
  {
    "id": "street-musician",
    "role": "street musician"
  },
  {
    "id": "delivery-courier",
    "role": "delivery courier"
  },
  {
    "id": "barista",
    "role": "barista"
  },
  {
    "id": "security-guard",
    "role": "security guard"
  },
  {
    "id": "tourist",
    "role": "tourist"
  },
  {
    "id": "shop-owner",
    "role": "shop owner"
  },
  {
    "id": "city-maintenance-worker",
    "role": "city maintenance worker"
  },
  {
    "id": "bike-courier",
    "role": "bike courier"
  },
  {
    "id": "retired-teacher-out-for-a-walk",
    "role": "retired teacher out for a walk"
  },
  {
    "id": "food-truck-chef",
    "role": "food truck chef"
  }
];
